### ISSUE TITLE
Enabled for Momo but it still detect "Debugging mode is enabled"

### ISSUE THREAD

**Issue by BadIDMan** [xfqwdsj/IAmNotADeveloper#19]
Running Android 9 custom ROM with Magisk 26.1 and Zygisk - LSPosed v1.8.6 (6712)
Just installed "IAmNotADeveloper" version 1.0.2 and enabled this module for Momo 4.4.1 but still in Momo there is Suspicious trace found: "Debugging mode is enabled"
So don't know what "IAmNotADeveloper" is doing but for sure it doesn't hide debug mode from detection in Momo.
Also tried to enable "IAmNotADeveloper" for Magisk. The same result - still in Momo "Debugging mode is enabled" is detected.

**Comment by xfqwdsj** [comment]
See https://github.com/xfqwdsj/IAmNotADeveloper/issues/4#issuecomment-1264386917
