### ISSUE TITLE
Momo 4.4.1/Ruru 1.1.0 still detects USB debugging

### ISSUE THREAD

**Issue by privacyguy123** [xfqwdsj/IAmNotADeveloper#24]
See title.

**Comment by xfqwdsj** [comment]
See https://github.com/xfqwdsj/IAmNotADeveloper/issues/4#issuecomment-1264386917 and https://github.com/xfqwdsj/IAmNotADeveloper/issues/9.

**Comment by privacyguy123** [comment]
> See [#4 (comment)](https://github.com/xfqwdsj/IAmNotADeveloper/issues/4#issuecomment-1264386917) and #9.

Does this mean you can't fix it?

**Comment by xfqwdsj** [comment]
Yes, I'll try to intercept more methods of getting debug mode status, but still can't get around XposedDetector. If at some future date I push out an update for this module, Momo or Ruru's detection may still not be bypassable.
