### ISSUE TITLE
支持BL解锁隐藏.

### ISSUE THREAD

**Issue by daiaji** [xfqwdsj/IAmNotADeveloper#37]
https://github.com/chiteroman/BootloaderSpoofer
集成一下吧。
对momo启用xposed模块的话都会被反制？
> Thanks to [Pine ](https://github.com/canyie/pine)now we can hook Java methods + JNI methods + C code + patch instructions.

https://xdaforums.com/t/spoof-locked-bootloader-bypass-tee-check.4586251/post-88652491

Pine有搞头吗？

**Comment by xfqwdsj** [comment]
> 集成一下吧。

这个项目貌似还在维护，目前看来好像没有必要加入它

> 对momo启用xposed模块的话都会被反制？

是的，我曾经看到过 XposedDetector 的源代码 ~~，但是很可惜我没有保存它~~ 。有人 Fork 了它，我也把它弄过来了，嘿嘿😁。

> Pine有搞头吗？

既然源代码到手了，我就找时间看看吧，不过就不知道什么时候能看了。

**Comment by xfqwdsj** [comment]
如果没有别的信息，我关闭这个 Issue
