### ISSUE TITLE
支持隐藏mock location

### ISSUE THREAD

**Issue by Lovefish** [xfqwdsj/IAmNotADeveloper#39]
好像有实现这个功能的模块，但是不知道功能是否有用。看是否能够改进。支持最新系统a14，然后添加进该模块。

**Comment by xfqwdsj** [comment]
是否可以提供一些源代码方便我快速参考？

**Comment by Lovefish** [comment]
> 是否可以提供一些源代码方便我快速参考？

https://github.com/ThePieMonster/HideMockLocation

**Comment by xfqwdsj** [comment]
可以添加，但我目前在维护其他项目。如果可以，欢迎贡献

**Comment by Lovefish** [comment]
> 可以添加，但我目前在维护其他项目。如果可以，欢迎贡献

我能力有限😅
这个fork也可以参考
https://github.com/emotionbug/HideMockLocation

**Comment by xfqwdsj** [comment]
> <https://github.com/emotionbug/HideMockLocation>

这好像是一个正在维护的项目。你测试过它的功能是否有效吗？

**Comment by Lovefish** [comment]
> > https://github.com/emotionbug/HideMockLocation
> 
> 这好像是一个正在维护的项目。你测试过它的功能是否有效吗？

我测试的几个有效。
上游那个项目好像也是有效的，这两个到底有什么区别我也不知道。

Mock location选择用这一个app https://github.com/ZCShou/GoGoGo
需要虚拟定位的APP如果没有用hide模块的话是不生效的，勾选了之后才会生效。

**Comment by xfqwdsj** [comment]
既然它还能用，就暂时不考虑
