### ISSUE TITLE
Halifax crashing when enabled with IAmNotADeveloper

### ISSUE THREAD

**Issue by Aracnoss** [xfqwdsj/IAmNotADeveloper#45]
**Describe the bug**
When enabling this with Halifax app, it will crash when attempting to sign in

**To Reproduce**
1. Enable Halifax in LSposed with IAmNotADeveloper
2. Clear Halifax storage/cache, reboot phone
3. Launch IAmNotADeveloper and verify active
4. Launch Halifax and attempt to sign in
5. Halifax with either crash or freeze/reload

**Expected behavior**
Halifax app does not crash/reload when attempting to sign in.

**Smartphone (please complete the following information):**
 - Device: Pixel 7
 - OS: Android 13

**Additional context**
I'm guessing it's crashing at the moment it attempts to read properties around developer settings, as it usually locks you out on signing in.
I have ran the app, without this enabled, and it just locks you out detecting root.
I've verified this doesn't happen with a couple of other banking apps, so likely specifically a Halifax app issue.

**Comment by westruk** [comment]
Working fine with latest version
![Screenshot_20240117-114731_Halifax.png](https://github.com/xfqwdsj/IAmNotADeveloper/assets/64413688/708f362c-00b3-4c15-ac4e-474bf892e78d)

![Screenshot_20240117-114422_Оболочка.png](https://github.com/xfqwdsj/IAmNotADeveloper/assets/64413688/d34fea2b-a024-4cfa-9112-fc6278515ebc)

**Comment by Aracnoss** [comment]
Hey @xfqwdsj,

It crashes after you attempt to sign in by clicking through "Let's get you signed in" -> "sign in now".
Not on the home page of the app.

**Comment by westruk** [comment]
> Hey @xfqwdsj,
> 
> It crashes after you attempt to sign in by clicking through "Let's get you signed in" -> "sign in now".
> Not on the home page of the app.

![Screenshot_20240117-204505_Halifax.png](https://github.com/xfqwdsj/IAmNotADeveloper/assets/64413688/5dec5c29-839a-4550-b695-4208646bab82)

**Comment by xfqwdsj** [comment]
Please add more information about the environment: Magisk version, LSPosed version, Magisk module list, LSPosed module list.

Let's see if we can find more clues from here. 🤔

**Comment by xfqwdsj** [comment]
I likewise got crashes when trying to sign in and adb disabled. Maybe some modules are leaking the environment.

**Comment by xfqwdsj** [comment]
Because after 10 days there is still no response, close this issue. Reopen it when you have more information.
