### ISSUE TITLE
Not hiding development mode

### ISSUE THREAD

**Issue by gabriel20xx** [xfqwdsj/IAmNotADeveloper#79]
**Describe the bug**
The module is not working for me. Ruru and other apps detect development mode as enabled.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Poco F3
 - OS: CrDroid, Android 14

**Additional context**

**Comment by xfqwdsj** [comment]
Show me your test result

![Result](https://github.com/user-attachments/assets/96db2366-7800-42d1-9aac-973f4bf4cd99)

**Comment by xfqwdsj** [comment]
May be duplicate of #4

**Comment by gabriel20xx** [comment]
> Show me your test result
> 
> ![Result](https://github.com/user-attachments/assets/96db2366-7800-42d1-9aac-973f4bf4cd99)
> 

The test result is like it should be, but it's not working with other apps

**Comment by xfqwdsj** [comment]
No enough information, consider this as a duplicate of #4.
